"""add fields to logs table

Revision ID: 4f5034521db7
Revises: 78f2d4ea2474
Create Date: 2026-04-11 08:01:18.107729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5034521db7'
down_revision: Union[str, None] = '78f2d4ea2474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('method', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'ip')
    op.drop_column('logs', 'duration_ms')
    op.drop_column('logs', 'status_code')
    op.drop_column('logs', 'method')
    # ### end Alembic commands ###
