"""add metadata and soft delete to items

Revision ID: 78acc9b0067b
Revises: f47e87a4b765
Create Date: 2026-03-21 11:28:44.776928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78acc9b0067b'
down_revision: Union[str, None] = 'f47e87a4b765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'is_deleted')
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
