"""add is_active and refresh_tokens

Revision ID: 78f2d4ea2474
Revises: 270ebe86c754
Create Date: 2026-04-05 12:21:08.683846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f2d4ea2474'
down_revision: Union[str, None] = '270ebe86c754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
